# Generated by Django 3.0.8 on 2021-10-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidoApi', '0001_initial'),
        ('servicesApi', '0001_initial'),
        ('usersApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='idpcliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApi.Cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='idproveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersApi.Proveedor'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='idservicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicesApi.Servicio'),
        ),
    ]
