# Generated by Django 3.0.8 on 2021-11-06 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidoApi', '0003_auto_20211019_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='invoiceNumber',
        ),
    ]
