# Generated by Django 3.0.8 on 2021-10-18 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApi', '0002_auto_20211018_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
