# Generated by Django 3.0.8 on 2021-10-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApi', '0003_auto_20211018_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saldo',
            field=models.FloatField(default=0, null=True),
        ),
    ]
