# Generated by Django 3.0.8 on 2021-10-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idservice', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('price_hour', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
