# Generated by Django 3.0.8 on 2021-10-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicesApi', '0001_initial'),
        ('usersApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='idproveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usersApi.Proveedor'),
        ),
    ]
