# Generated by Django 3.0.8 on 2021-10-19 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicesApi', '0002_servicio_idproveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='idproveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
